spring:
  application:
    name: perftesttest
  datasource:
    url: jdbc:mysql://localhost:3306/KKODB?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    database: mysql

server:
  port: 14404
